language: objective-c

branches:
 only:
 - master

xcode_project: DataDecoder.xcodeproj
xcode_scheme: DataDecoderTests
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.0

script:
- xcodebuild clean build test -project DataDecoder.xcodeproj -scheme DataDecoderTests
