language: objective-c

branches:
 only:
 - master

xcode_project: DataDecoder.xcodeproj
xcode_scheme: DataDecoderTests
os: osx
osx_image: xcode9.0
xcode_sdk: iphonesimulator11.0

script:
- xcodebuild clean build test -project DataDecoder.xcodeproj -scheme DataDecoderTests
